Moved Clear/DistSkel procedures in remastersys-gui to remastersys-skelcopy. Updated translations.

diff --git a/remastersys/usr/bin/remastersys-skelcopy b/remastersys/usr/bin/remastersys-skelcopy
--- a/remastersys/usr/bin/remastersys-skelcopy
+++ b/remastersys/usr/bin/remastersys-skelcopy
@@ -19,94 +19,119 @@ usagehelp(){
     echo " "
     echo $"USAGE:"
     echo " "
-    echo $"   remastersys-skelcopy [username]"
-    echo $"      (username is a valid user on the system)"
+    echo $"   remastersys-skelcopy [username|clear]"
+    echo " "
+    echo -e $"      username   - is a valid user on the system. Copies \"username\" personal\n                   settings to the /etc/skel folder."
+    echo $"      clear      - deletes all contents of /etc/skel."
     echo " "
     exit 1
 }
 
 # check if running with root privileges
 if [ $(whoami) != "root" ]; then
-    echo $"ERROR: This script must run as superuser. Try with \"sudo\"."
+    echo -e $"$fB$fLightRed\nERROR: This script must run as superuser. Try with \"sudo\".\n$fEND"
     usagehelp
 fi
+
+backupSkel(){
+    if [ ! -d /etc/remastersys/skel-backup ]; then
+        mkdir /etc/remastersys/skel-backup
+        cp /etc/skel/{\*,.*} /etc/remastersys/skel-backup
+    fi
+}
 
 if [ "$1" = "help" -o "$1" = "--help" -o "$1" = "" ]; then
     usagehelp
-fi
-
-SKELUSER="$1"
-
-SKELFOLDER=`grep "^$SKELUSER:" /etc/passwd | awk -F ":" '{print $6}'`
-
-if [ -d "$SKELFOLDER" ]; then
-    cd $SKELFOLDER
-    echo $"Cleaning up /etc/skel of the files we will copy over."
-    rm -rf /etc/skel/.bacon
-    rm -rf /etc/skel/.xscreensaver
-    rm -rf /etc/skel/.gconf
-    rm -rf /etc/skel/.bashrc
-    rm -rf /etc/skel/.profile
-    rm -rf /etc/skel/.gconf
-    rm -rf /etc/skel/.gnome2
-    rm -rf /etc/skel/.config
-    rm -rf /etc/skel/.local
-    rm -rf /etc/skel/.icewm*
-    rm -rf /etc/skel/.fvwm*
-    rm -rf /etc/skel/.afterstep*
-    rm -rf /etc/skel/.gtkrc*
-    rm -rf /etc/skel/.mate*
-    rm -rf /etc/skel/.qt*
-    rm -rf /etc/skel/.kde*
-    rm -rf /etc/skel/.pekwm
-    rm -rf /etc/skel/.razor
-    rm -rf /etc/skel/.wbar
-    rm -rf /etc/skel/.mplayer
-    echo $"Copying config files to /etc/skel."
-    rsync -a .bacon /etc/skel/
-    rsync -a .xscreensaver /etc/skel
-    sed -i -e "s/$SKELUSER//g" /etc/skel/.xscreensaver
-    rsync -a .gconf /etc/skel/
-    rsync -a .bashrc /etc/skel/
-    rsync -a .profile /etc/skel/
-    rsync -a .gnome2 /etc/skel/
-    rsync -a .config /etc/skel/
-    rsync -a .local /etc/skel/
-    rsync -a .icewm* /etc/skel/
-    rsync -a .fvwm* /etc/skel/
-    rsync -a .afterstep* /etc/skel/
-    rsync -a .mate* /etc/skel/
-    rsync -a .gtkrc* /etc/skel/
-    rsync -a .qt* /etc/skel/
-    rsync -a .kde* /etc/skel/
-    rsync -a .pekwm /etc/skel/
-    rsync -a .razor /etc/skel/
-    rsync -a .wbar /etc/skel/
-    rsync -a .mplayer /etc/skel/
-    rm -rf /etc/skel/.config/chromium
-    rm -rf /etc/skel/.config/midori/cookies.*
-    rm -rf /etc/skel/.config/midori/history.*
-    rm -rf /etc/skel/.config/midori/tabtrash.*
-    rm -rf /etc/skel/.config/midori/running*
-    rm -rf /etc/skel/.config/midori/bookmarks.*
-    rm -rf /etc/skel/.config/user-dirs.*
-    rm -rf /etc/skel/.gconf/system/networking
-    rm -rf /etc/skel/.local/gvfs-metadata
-    rm -rf /etc/skel/.local/share/gvfs-metadata
-    rm -rf /etc/skel/.local/share/applications/wine-*
-    rm -rf /etc/skel/.local/share/Trash
-    rm -rf /etc/skel/.local/share/akonadi
-    rm -rf /etc/skel/.local/share/webkit
-    rm -rf /etc/skel/.kde/share/apps/klipper
-    rm -rf /etc/skel/.kde/share/apps/nepomuk
-    rm -rf /etc/skel/.kde/share/apps/RecentDocuments/*
-    for i in /etc/skel/.gnome2/keyrings/*; do rm $i; done
-    find /etc/skel/ | grep "$SKELUSER" | xargs rm -rf '{}'
-    find /etc/skel/ -name "*socket*" | xargs rm -rf '{}'
-    find /etc/skel/ -name "*cache*" | xargs rm -rf '{}'
-    grep -Rl "$SKELUSER" /etc/skel | xargs rm -rf '{}'
-    chown -R root:root /etc/skel
+elif [ "$1" = "clear" ]; then
+    # First: make a backup of Debian original files if there is no backup
+    backupSkel
+    
+    # Second: clear skel
+    rm -rf /etc/skel/{\*,.*}
+    
+    # Third: if there is a backup of Debian original files, restore it
+    if [ -d /etc/remastersys/skel-backup ]; then
+        cp /etc/remastersys/skel-backup/{\*,.*} /etc/skel/
+        rm -rf /etc/remastersys/skel-backup
+    fi
 else
-    echo $"$1 either not found or doesn't have a proper home folder. Exiting."
-    exit 1
+    # First: make a backup of Debian original files if there is no backup
+    backupSkel
+    
+    SKELUSER="$1"
+
+    SKELFOLDER=$(grep "^$SKELUSER:" /etc/passwd | awk -F ":" '{print $6}')
+
+    if [ -d "$SKELFOLDER" ]; then
+        cd $SKELFOLDER
+        echo $"Cleaning up /etc/skel of the files we will copy over."
+        rm -rf /etc/skel/.bacon
+        rm -rf /etc/skel/.xscreensaver
+        rm -rf /etc/skel/.gconf
+        rm -rf /etc/skel/.bashrc
+        rm -rf /etc/skel/.profile
+        rm -rf /etc/skel/.gconf
+        rm -rf /etc/skel/.gnome2
+        rm -rf /etc/skel/.config
+        rm -rf /etc/skel/.local
+        rm -rf /etc/skel/.icewm*
+        rm -rf /etc/skel/.fvwm*
+        rm -rf /etc/skel/.afterstep*
+        rm -rf /etc/skel/.gtkrc*
+        rm -rf /etc/skel/.mate*
+        rm -rf /etc/skel/.qt*
+        rm -rf /etc/skel/.kde*
+        rm -rf /etc/skel/.pekwm
+        rm -rf /etc/skel/.razor
+        rm -rf /etc/skel/.wbar
+        rm -rf /etc/skel/.mplayer
+        echo $"Copying config files to /etc/skel."
+        rsync -a .bacon /etc/skel/
+        rsync -a .xscreensaver /etc/skel
+        sed -i -e "s/$SKELUSER//g" /etc/skel/.xscreensaver
+        rsync -a .gconf /etc/skel/
+        rsync -a .bashrc /etc/skel/
+        rsync -a .profile /etc/skel/
+        rsync -a .gnome2 /etc/skel/
+        rsync -a .config /etc/skel/
+        rsync -a .local /etc/skel/
+        rsync -a .icewm* /etc/skel/
+        rsync -a .fvwm* /etc/skel/
+        rsync -a .afterstep* /etc/skel/
+        rsync -a .mate* /etc/skel/
+        rsync -a .gtkrc* /etc/skel/
+        rsync -a .qt* /etc/skel/
+        rsync -a .kde* /etc/skel/
+        rsync -a .pekwm /etc/skel/
+        rsync -a .razor /etc/skel/
+        rsync -a .wbar /etc/skel/
+        rsync -a .mplayer /etc/skel/
+        rm -rf /etc/skel/.config/chromium
+        rm -rf /etc/skel/.config/midori/cookies.*
+        rm -rf /etc/skel/.config/midori/history.*
+        rm -rf /etc/skel/.config/midori/tabtrash.*
+        rm -rf /etc/skel/.config/midori/running*
+        rm -rf /etc/skel/.config/midori/bookmarks.*
+        rm -rf /etc/skel/.config/user-dirs.*
+        rm -rf /etc/skel/.gconf/system/networking
+        rm -rf /etc/skel/.local/gvfs-metadata
+        rm -rf /etc/skel/.local/share/gvfs-metadata
+        rm -rf /etc/skel/.local/share/applications/wine-*
+        rm -rf /etc/skel/.local/share/Trash
+        rm -rf /etc/skel/.local/share/akonadi
+        rm -rf /etc/skel/.local/share/webkit
+        rm -rf /etc/skel/.kde/share/apps/klipper
+        rm -rf /etc/skel/.kde/share/apps/nepomuk
+        rm -rf /etc/skel/.kde/share/apps/RecentDocuments/*
+        for i in /etc/skel/.gnome2/keyrings/*; do rm $i; done
+        find /etc/skel/ | grep "$SKELUSER" | xargs rm -rf '{}'
+        find /etc/skel/ -name "*socket*" | xargs rm -rf '{}'
+        find /etc/skel/ -name "*cache*" | xargs rm -rf '{}'
+        grep -Rl "$SKELUSER" /etc/skel | xargs rm -rf '{}'
+        chown -R root:root /etc/skel
+    else
+        echo $"$1 either not found or doesn't have a proper home folder. Exiting."
+        exit 1
+    fi
 fi
+
