FORK: first commit. I have imported the source code from an old fork I was developing.

diff --git a/remastersys/usr/bin/remastersys-grubconfig b/remastersys/usr/bin/remastersys-grubconfig
--- a/remastersys/usr/bin/remastersys-grubconfig
+++ b/remastersys/usr/bin/remastersys-grubconfig
@@ -1,83 +1,96 @@
 #!/bin/bash
+###################################################################
+#  REMASTERSYS                                                    #
+#    Under the GNU GPL2 License                                   #
+#    Copyright (C) 2013-2021 Daniel "Nerun" Rodrigues             #
+#    Copyright (C) 2007-2012 Tony "Fragadelic" Brijeski           #
+#    Full copyright notice: /usr/share/doc/remastersys/copyright  #
+###################################################################
 
-# remastersys-grubconfig
-# by Tony Brijeski (c)2009 GPLv2
+# SYSTEM LOCALIZATION
+# Target to file:
+# /usr/share/locale/(language code)/LC_MESSAGES/remastersys-grubconfig.mo
+TEXTDOMAIN=remastersys-grubconfig
 
-if [ "$1" = "" ]; then
-echo
-echo "Usage is remastersys-grubconfig /mountedlocation [root|rootmbr]"
-echo
-echo "/mountedlocation                  You must specify the full path"
-echo "root                       Install grub to root partition"
-echo "                           MBR will be used if no option present"
-echo
-echo
-echo "eg. to install to root partition of the current install"
-echo
-echo "    remastersys-grubconfig / root"
-echo
-echo
-echo "eg. to install to mbr on a mounted drive - if running from livecd"
-echo
-echo "    remastersys-grubconfig /mnt/sda1"
-echo
-exit 1
+# LIBRARIES
+. /usr/lib/remastersys/remastersys.so
+
+usagehelp(){
+	echo " "
+	echo $"USAGE:"
+	echo " "
+	echo $"   remastersys-grubconfig [/mounted/location] [root|rootmbr]"
+	echo $"      (must run as superuser)"
+	echo " "
+	echo $"   /mounted/location - You must specify the full path"
+	echo $"   root              - Install grub to root partition"
+	echo $"   rootmbr           - Default. MBR will be used if no option present"
+	echo " "
+	echo $"EXAMPLES:"
+	echo " "
+	echo "   remastersys-grubconfig / root"
+	echo $"      (install to root partition of the current install)"
+	echo " "
+	echo "   remastersys-grubconfig /mnt/sda1"
+	echo $"      (install to mbr on a mounted drive, if running from Live CD)"
+	echo " "
+	exit 1
+}
+
+# check if running with root privileges
+if [ $(whoami) != "root" ]; then
+    echo $"ERROR: This script must run as superuser. Try with \"sudo\"."
+    usagehelp
 fi
 
-testroot="`whoami`"
-
-if [ "$testroot" != "root" ]; then
-echo "remastersys-grubconfig must be run with root privileges."
-exit 1
+if [ "$1" = "help" -o "$1" = "--help" -o "$1" = "" ]; then
+    usagehelp
 fi
 
 ROOTMOUNT="$1"
+
 if [ "$ROOTMOUNT" = "" ]; then
-ROOTMOUNT="/"
+	ROOTMOUNT="/"
 fi
 
 ROOTPART=`mount | grep " $ROOTMOUNT " | awk '{print $1}'`
 ROOTMBR=`echo $ROOTPART | sed -e 's/[1-9]//g'`
 GRUBLOCTEST="$2"
+
 if [ "$GRUBLOCTEST" = "root" ]; then
-GRUBLOC="$ROOTPART"
-echo $GRUBLOC
+	GRUBLOC="$ROOTPART"
+	echo $GRUBLOC
 elif [ "$GRUBLOCTEST" = "rootmbr" ]; then
-GRUBLOC="$ROOTMBR"
-echo $GRUBLOC
+	GRUBLOC="$ROOTMBR"
+	echo $GRUBLOC
 else
-GRUBLOC="/dev/sda"
-echo $GRUBLOC
+	GRUBLOC="/dev/sda"
+	echo $GRUBLOC
 fi
-
-
 
 if [ "$ROOTMOUNT" != "/" ]; then
+	if [ ! -e $ROOTMOUNT/proc/cpuinfo ]; then
+		STANDALONE="yes"
+		mount -o bind /proc $ROOTMOUNT/proc
+		mount -o bind /dev $ROOTMOUNT/dev
+		mount -o bind /sys $ROOTMOUNT/sys
+	fi
 
-if [ ! -e $ROOTMOUNT/proc/cpuinfo ]; then
-STANDALONE="yes"
-mount -o bind /proc $ROOTMOUNT/proc
-mount -o bind /dev $ROOTMOUNT/dev
-mount -o bind /sys $ROOTMOUNT/sys
-fi
-chroot $ROOTMOUNT grub-install --no-floppy $GRUBLOC
-chroot $ROOTMOUNT update-grub
-sync
-if [ "$STANDALONE" = "yes" ]; then
-sleep 1
-umount $ROOTMOUNT/proc
-sleep 1
-umount $ROOTMOUNT/dev
-sleep 1
-umount $ROOTMOUNT/sys
-sleep 1
-fi
+	chroot $ROOTMOUNT grub-install --no-floppy $GRUBLOC
+	chroot $ROOTMOUNT update-grub
+	sync
+
+	if [ "$STANDALONE" = "yes" ]; then
+		sleep 1
+		umount $ROOTMOUNT/proc
+		sleep 1
+		umount $ROOTMOUNT/dev
+		sleep 1
+		umount $ROOTMOUNT/sys
+		sleep 1
+	fi
 else
-grub-install --no-floppy $GRUBLOC
-update-grub
-sync
+	grub-install --no-floppy $GRUBLOC
+	update-grub
+	sync
 fi
-
-
-
-
